server:
  port: 8087
spring:
  application:
    name: warehouse-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
feign:
  hystrix:
    enabled: true